apiVersion: apps/v1
kind: Deployment
metadata:
    name: example
    namespace: default
spec:
    selector:
        matchLabels:
            app: example
    replicas: 2
    template:
        metadata:
            labels:
                app: example
        spec:
            containers:
                - name: example
                  image: local/example:latest
                  ports:
                      - containerPort: 4499
