apiVersion: apps/v1
kind: Deployment
metadata:
    name: wisecow
    namespace: default
spec:
    selector:
        matchLabels:
            app: wisecow
    replicas: 2
    template:
        metadata:
            labels:
                app: wisecow
        spec:
            containers:
                - name: wisecow
                  image: local/wisecow:latest
                  ports:
                      - containerPort: 4499
