apiVersion: v1
kind: Service
metadata:
  name: wisecow
spec:
  type: NodePort  # Expose internally within Minikube
  selector:
    app: wisecow
  ports:
  - port: 80  # Internal port
    targetPort: 4499

