name: Build, Push, and Deploy to Minikube

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start minikube
        run: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t bababund/wisecow .
          echo -n "verifying images:"
          docker images   
        
      - name: Deploy to minikube
        run: kubectl apply -f deployment.yaml -f service.yaml

      - name: Test service URLs
        run: |
          minikube service list
          minikube service wisecow --url
          echo "------------------opening the service------------------"
          curl $(minikube service wisecow --url)    



