name: Build and Deploy to Minikube on PR

on:
  pull_request:

jobs:
  deploy-to-minikube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and start Minikube
        uses: appleboy/minikube-runner@v0.15.0  # Replace with a working action

      - name: Set up Docker for Minikube
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t local/wisecow .

      - name: Set up kubectl for Minikube
        run: kubectl config set-cluster minikube

      - name: Apply Kubernetes manifests
        run: kubectl apply -f deployment.yaml -f service.yaml  # Adjust paths if needed

      - name: Verify application health (optional)
        run: kubectl exec -it wisecow -- sh -c "curl -I http://localhost:80/ | head"  # Adjust command as needed

