name: Build, Push, and Deploy to Minikube

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -t local/wisecow:latest . 
        echo -n "verifying images:"
        docker images    
        
    - name: Try the cluster !
      run: |
        kubectl create deployment example --image=wisecow
        kubectl get pods 
    - name: Deploy to minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl get svc wisecow
    - name: Test service URLs
      run: |
        minikube service list
        minikube service wisecow --url
        echo "------------------opening the service------------------"
        curl $(minikube service wisecow --url)        


